package eg.gov.iti.jets.shopifyapp_user.cart.domain.model

data class DraftOrder(
    val admin_graphql_api_id: String,
    val applied_discount: Any?,
    val billing_address: Any?,
    val completed_at: Any?,
    val created_at: String,
    val currency: String,
    val email: Any?,
    val id: Long,
    val invoice_sent_at: Any?,
    val invoice_url: String,
    val line_items: List<LineItem>,
    val name: String,
    val note: Any?,
    val note_attributes: List<Any>,
    val order_id: Any?,
    val payment_terms: Any?,
    val shipping_address: Any?,
    val shipping_line: Any?,
    val status: String,
    val subtotal_price: Double,
    val tags: String,
    val tax_exempt: Boolean,
    val tax_lines: List<TaxLineX>,
    val taxes_included: Boolean,
    val total_price: Double,
    val total_tax: Double,
    val updated_at: String
)