package eg.gov.iti.jets.shopifyapp_user.cart.domain.model

data class DraftOrder(
    var admin_graphql_api_id: String,
    var applied_discount: AppliedDiscount,
    var billing_address: Any,
    var completed_at: Any,
    var created_at: String,
    var currency: String,
    var email: Any,
    var id: Long,
    var invoice_sent_at: Any,
    var invoice_url: String,
    var line_items: List<LineItem>,
    var name: String,
    var note: Any,
    var note_attributes: List<Any>,
    var order_id: Any,
    var payment_terms: Any,
    var shipping_address: Any,
    var shipping_line: Any,
    var status: String,
    var subtotal_price: String,
    var tags: String,
    var tax_exempt: Boolean,
    var tax_lines: List<TaxLineX>,
    var taxes_included: Boolean,
    var total_price: String,
    var total_tax: String,
    var updated_at: String
)